version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: privacy_rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol (used by pika)
      - "15672:15672"   # Management UI
    # environment:
    #   RABBITMQ_DEFAULT_USER: guest
    #   RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped